version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: oms
      POSTGRES_USER: oms
      POSTGRES_PASSWORD: oms@123
    ports:
      - "5443:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?search_path=testdb
      SPRING_DATASOURCE_USERNAME: oms
      SPRING_DATASOURCE_PASSWORD: oms@123
