version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: roma
      POSTGRES_PASSWORD: roma@123
    ports:
      - "5438:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: roma
      SPRING_DATASOURCE_PASSWORD: roma@123
