server:
  port: ${PORT:${SERVER_PORT:8080}}
  address: 0.0.0.0
spring:
  application:
    name: training-application
  devtools:
    add-properties: false
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: roma
    password: roma@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev

