server:
  port: 8090

spring:
  application:
    name: training-application

---
spring:
  datasource:
    url: jdbc:postgresql://database-1.cnya44sew6fx.us-east-1.rds.amazonaws.com:5432/oms
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev
